// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID
	Username     string
	Password     string
	Email        string
	RefreshToken sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
